-- ============================================================
-- NOVATECH SOLUTIONS - SUPABASE SETUP SQL
-- Saare tables + RLS policies ek saath
-- Run this in: Supabase Dashboard > SQL Editor > New Query
-- ============================================================

-- ============================================================
-- 1. CONTACT MESSAGES (SABSE ZAROORI - Contact form ke liye)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new',          -- new | read | replied | archived
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional: Email pe quick filter ke liye index
CREATE INDEX IF NOT EXISTS idx_contact_messages_email ON public.contact_messages(email);
CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at ON public.contact_messages(created_at DESC);

-- ============================================================
-- 2. PORTFOLIO PROJECTS (portfolio.html ke liye)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.portfolio_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('web', 'mobile', 'design')),
    image_url TEXT,
    project_url TEXT,
    tags TEXT[],  -- jaise {'React', 'Node.js'}
    is_published BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 3. TESTIMONIALS (portfolio.html ke testimonials section)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.testimonials (
    id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_role TEXT,           -- jaise 'CEO, TechStart Inc.'
    quote TEXT NOT NULL,
    rating SMALLINT DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
    is_published BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 4. TEAM MEMBERS (about.html ke liye)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.team_members (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    bio TEXT,
    avatar_url TEXT,
    email TEXT,
    linkedin_url TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 5. SERVICES (services.html ke liye - optional)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.services (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon TEXT,                    -- emoji ya icon class e.g. '🌐'
    features JSONB NOT NULL DEFAULT '[]',  -- array of strings
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 6. PRICING PLANS (services.html me pricing section)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.pricing_plans (
    id SERIAL PRIMARY KEY,
    plan_name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    description TEXT,
    features JSONB NOT NULL DEFAULT '[]',
    is_featured BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 7. NEWSLETTER SUBSCRIBERS (agar future me newsletter ho)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'subscribed',  -- subscribed | unsubscribed | bounced
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================

-- Enable RLS on ALL tables
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- CONTACT MESSAGES
-- Public: koi bhi message send kar sakta hai (INSERT only)
-- Admin (Authenticated): delete messages dekh/sakta hai, update read status
-- ------------------------------------------------------------
CREATE POLICY "Public can insert contact messages"
    ON public.contact_messages FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Authenticated can read contact messages"
    ON public.contact_messages FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update contact messages"
    ON public.contact_messages FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can delete contact messages"
    ON public.contact_messages FOR DELETE
    USING (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- PORTFOLIO PROJECTS
-- Public: sirf published projects dekh sakta hai
-- Admin: CRUD sab kuch
-- ------------------------------------------------------------
CREATE POLICY "Public can view published portfolio projects"
    ON public.portfolio_projects FOR SELECT
    USING (is_published = true OR auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert portfolio projects"
    ON public.portfolio_projects FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update portfolio projects"
    ON public.portfolio_projects FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can delete portfolio projects"
    ON public.portfolio_projects FOR DELETE
    USING (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- TESTIMONIALS
-- ------------------------------------------------------------
CREATE POLICY "Public can view published testimonials"
    ON public.testimonials FOR SELECT
    USING (is_published = true OR auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert testimonials"
    ON public.testimonials FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update testimonials"
    ON public.testimonials FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can delete testimonials"
    ON public.testimonials FOR DELETE
    USING (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- TEAM MEMBERS
-- ------------------------------------------------------------
CREATE POLICY "Public can view active team members"
    ON public.team_members FOR SELECT
    USING (is_active = true OR auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert team members"
    ON public.team_members FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update team members"
    ON public.team_members FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can delete team members"
    ON public.team_members FOR DELETE
    USING (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- SERVICES
-- ------------------------------------------------------------
CREATE POLICY "Public can view active services"
    ON public.services FOR SELECT
    USING (is_active = true OR auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert services"
    ON public.services FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update services"
    ON public.services FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can delete services"
    ON public.services FOR DELETE
    USING (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- PRICING PLANS
-- ------------------------------------------------------------
CREATE POLICY "Public can view active pricing plans"
    ON public.pricing_plans FOR SELECT
    USING (is_active = true OR auth.role() = 'authenticated');

CREATE POLICY "Authenticated can insert pricing plans"
    ON public.pricing_plans FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update pricing plans"
    ON public.pricing_plans FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can delete pricing plans"
    ON public.pricing_plans FOR DELETE
    USING (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- NEWSLETTER SUBSCRIBERS
-- Public: koi bhi subscribe kar sakta hai (INSERT)
-- Admin: manage kar sakta hai
-- ------------------------------------------------------------
CREATE POLICY "Anyone can subscribe to newsletter"
    ON public.newsletter_subscribers FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Authenticated can view newsletter subscribers"
    ON public.newsletter_subscribers FOR SELECT
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can update newsletter subscribers"
    ON public.newsletter_subscribers FOR UPDATE
    USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated can delete newsletter subscribers"
    ON public.newsletter_subscribers FOR DELETE
    USING (auth.role() = 'authenticated');

-- ============================================================
-- SAMPLE DATA (Optional - sirf jab chahein sample data daalein)
-- ============================================================
INSERT INTO portfolio_projects (title, description, category, image_url, project_url, tags)
VALUES
    ('E-Commerce Platform', 'Full-featured online store with payment integration', 'web', NULL, NULL, ARRAY['React', 'Node.js']),
    ('Fitness Tracker App', 'Cross-platform mobile app for health goals', 'mobile', NULL, NULL, ARRAY['Flutter', 'Firebase']),
    ('Brand Identity Design', 'Complete brand redesign with guidelines', 'design', NULL, NULL, ARRAY['Illustrator', 'Figma']);

INSERT INTO testimonials (client_name, client_role, quote, is_published)
VALUES
    ('John Smith', 'CEO, TechStart Inc.', 'NovaTech transformed our online presence. Sales increased 200%.', true),
    ('Lisa Park', 'Founder, GreenLeaf Co.', 'Outstanding attention to detail. Delivered ahead of schedule.', true),
    ('David Kim', 'CTO, CloudBase', 'Their mobile app helped us reach a whole new audience.', true);

INSERT INTO team_members (name, role, bio, sort_order)
VALUES
    ('Alex Johnson', 'CEO & Founder', 'Visionary leader with 15+ years experience.', 1),
    ('Sarah Chen', 'Lead Developer', 'Full-stack expert in modern web technologies.', 2),
    ('Mike Rivera', 'UI/UX Designer', 'Creative designer focused on user-centered designs.', 3),
    ('Emily Watson', 'Project Manager', 'Every project delivered on time and budget.', 4);